steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
      - '--region=$_DEPLOY_REGION'
      - '--set-env-vars'
      - >-
        NODE_ENV=production,ML_API_URL=${_ML_API_URL},BUCKET_NAME=${_BUCKET_NAME}
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LOCATION: asia-southeast2
  _REPOSITORY: didow-api
  _IMAGE: didow-main-api
  _SERVICE_NAME: didow-api
  _DEPLOY_REGION: asia-southeast2
